
export type GameCategory = {
  id: string;
  name: string;
  words: string[];
  icon?: React.ComponentType<{ className?: string }>;
};

// For icons, you would typically import them, e.g., import { Film, Music } from "lucide-react";
// However, to keep this config simple, we'll handle icons in the CategorySelector component.

export const CATEGORIES: GameCategory[] = [
  {
    id: "movies",
    name: "Movies",
    words: [
      "AMADEUS", "SYNECDOCHE NEW YORK", "MULHOLLAND DRIVE", "STALKER", "PERSONA",
      "MEMENTO", "OLDBOY", "AKIRA", "CHUNGKING EXPRESS", "VERTIGO",
      "PSYCHO", "ERASERHEAD", "BLUE VELVET", "A CLOCKWORK ORANGE", "APOCALYPSE NOW",
      "TAXI DRIVER", "RAGING BULL", "GOODFELLAS", "RESERVOIR DOGS", "FARGO",
      "BARTON FINK", "MILLERS CROSSING", "BRAZIL", "VIDEODROME", "SCANNERS",
      "CRASH", "EX MACHINA", "ANNIHILATION", "HEREDITARY", "MIDSOMMAR",
      "DOGTOOTH", "THE LOBSTER", "RAW", "ANTICHRIST", "MELANCHOLIA",
      "DOGVILLE", "DANCER IN THE DARK", "PI", "REQUIEM FOR A DREAM", "MOONRISE KINGDOM",
      "FANTASTIC MR FOX", "ISLE OF DOGS", "GHOST DOG", "DEAD MAN", "UNDER THE SKIN",
      "BEING JOHN MALKOVICH", "ETERNAL SUNSHINE", "DONNIE DARKO", "LOST IN TRANSLATION", "THE SACRIFICE"
    ]
  },
  {
    id: "music",
    name: "Music Artists",
    words: [
      "APHEXTWIN", "AUTECHRE", "BOARDSOFCANADA", "SIGURROS", "COCTEAUTWINS",
      "MYBLOODYVALENTINE", "SLOWDIVE", "RIDEBAND", "SWANSBAND", "GODSPEED",
      "MOGWAI", "EXPLOSIONSINTHESKY", "TORTOISEBAND", "STEREOLAB", "CANBAND",
      "NEUBAND", "FAUSTBAND", "KRAFTWERK", "TANGERINEDREAM", "SUNRA",
      "CAPTAINBEEFHEART", "FRANKZAPPA", "VELVETUNDERGROUND", "NICKDRAKE", "TIMBUCKLEY",
      "KATEBUSH", "TALKTALK", "DEADCANDANCE", "THISMORTALCOIL", "NEUBAUTEN",
      "THROBBINGGRISTLE", "COILBAND", "NURSEWITHWOUND", "LAIBACH", "DEATHGRIPS",
      "JPEGMAFIA", "FKATWIGS", "ARCABAND", "YVESTUMOR", "ONEOHTRIX",
      "FLYINGLOTUS", "BONIVER", "FLEETFOXES", "GRIZZLYBEAR", "ANIMALCOLLECTIVE",
      "PAVEMENT", "GUIDEDBYVOICES", "SONICYOUTH", "DINOSAURJR", "PIXIES"
    ]
  },
  {
    id: "countries",
    name: "Countries",
    words: [
      "LIECHTENSTEIN", "LUXEMBOURG", "AZERBAIJAN", "UZBEKISTAN", "KYRGYZSTAN",
      "TAJIKISTAN", "TURKMENISTAN", "KAZAKHSTAN", "MONTENEGRO", "NORTHMACEDONIA",
      "BOSNIAHERZEGOVINA", "SLOVENIA", "CROATIA", "LITHUANIA", "ESTONIA",
      "LATVIA", "BELARUS", "MOLDOVA", "GEORGIACOUNTRY", "ARMENIA",
      "SEYCHELLES", "MAURITIUS", "COMOROS", "MALDIVES", "SRILANKA",
      "BANGLADESH", "MYANMAR", "CAMBODIA", "LAOS", "BHUTAN",
      "NEPAL", "MONGOLIA", "BRUNEI", "TIMORLESTE", "VANUATU",
      "TUVALU", "KIRIBATI", "NAURU", "PALAU", "MICRONESIA",
      "MARSHALLISLANDS", "SOLOMONISLANDS", "SAMOA", "TONGA", "FIJICOUNTRY",
      "GUYANA", "SURINAME", "BELIZE", "HONDURAS", "NICARAGUA"
    ]
  },
  {
    id: "animals",
    name: "Animals",
    words: [
      "AXOLOTL", "PANGOLIN", "NARWHAL", "OKAPI", "QUOKKA",
      "CAPYBARA", "AARDVARK", "ECHIDNA", "PLATYPUS", "TARSIER",
      "MANATEE", "ARMADILLO", "OPOSSUM", "WOMBAT", "KOOKABURRA",
      "CASSOWARY", "EMU", "KIWIBIRD", "TUATARA", "KOMODODRAGON",
      "GILAMONSTER", "CHAMELEON", "IGUANA", "GECKO", "SALAMANDER",
      "NEWT", "COELACANTH", "ANGLERFISH", "VIPERFISH", "BLOBFISH",
      "HAGFISH", "LAMPREY", "STINGRAY", "SEAHORSE", "JELLYFISH",
      "SQUID", "OCTOPUS", "NAUTILUS", "SLOTH", "LEMUR",
      "MEERKAT", "HYRAX", "BINTURONG", "FENNECFOX", "OCELOT",
      "SERVAL", "CARACAL", "IBEX", "CHINCHILLA", "JERBOA"
    ]
  }
];

export const MAX_INCORRECT_GUESSES = 6;

export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
